import type { FeedCard } from '@/types'

export const feedCards: FeedCard[] = [
  {
    id: '1',
    category: 'debt',
    title: "Your Student Loan Isn't an Emergency \u{1F9E0}",
    body: "Most student loans have fixed rates and income-driven repayment options. That means missing a Netflix payment actually hurts you more than your loan does. Prioritize high-interest debt (credit cards) first.",
    stat: "The average 2024 grad has $37k in student debt.",
    emoji: "\u{1F9E0}",
    gradient: "from-red-950 to-zinc-900",
  },
  {
    id: '2',
    category: 'debt',
    title: "Avalanche vs. Snowball: Which Wins? \u2744\uFE0F",
    body: "Avalanche method: pay minimums on all, throw extra at highest interest. Snowball: pay smallest balance first for wins. Avalanche saves more money. Snowball builds momentum.",
    stat: "Avalanche saves ~$1,200 on a $20k loan vs. snowball.",
    emoji: "\u2744\uFE0F",
    gradient: "from-red-950 to-zinc-900",
  },
  {
    id: '3',
    category: 'budgeting',
    title: "The 50/30/20 Rule Actually Works \uD83D\uDCCA",
    body: "50% of take-home goes to needs (rent, food, utilities). 30% to wants (going out, subscriptions). 20% to savings or debt payoff. Simple, flexible, and it works on any income.",
    stat: "On $2,000/month: $400 goes straight to your future.",
    emoji: "\uD83D\uDCCA",
    gradient: "from-blue-950 to-zinc-900",
  },
  {
    id: '4',
    category: 'budgeting',
    title: "You're Probably Leaking $47/Month \uD83D\uDC40",
    body: "Forgotten subscriptions, bank fees, and app charges add up fast. Do a 10-minute audit: check your last 3 bank statements for recurring charges you forgot about.",
    stat: "Average American wastes $47/mo on forgotten subscriptions.",
    emoji: "\uD83D\uDC40",
    gradient: "from-blue-950 to-zinc-900",
  },
  {
    id: '5',
    category: 'investing',
    title: "You Don't Need $10k to Start Investing \uD83D\uDCC8",
    body: "Apps like Fidelity and Schwab let you buy fractional shares for as little as $1. An S&P 500 index fund is the boring, proven way most professionals actually invest.",
    stat: "$50/month at 7% avg return = $8,200 in 10 years.",
    emoji: "\uD83D\uDCC8",
    gradient: "from-green-950 to-zinc-900",
  },
  {
    id: '6',
    category: 'investing',
    title: "What's a Roth IRA? Your Future Self Will Thank You \uD83C\uDFE6",
    body: "A Roth IRA lets your money grow tax-free. You pay taxes now, never pay them on gains. Contribute up to $7,000/year. Open one with $1 at Fidelity or Schwab.",
    stat: "$6,000 invested at 22 \u2192 $100k+ by 65.",
    emoji: "\uD83C\uDFE6",
    gradient: "from-green-950 to-zinc-900",
  },
  {
    id: '7',
    category: 'credit',
    title: "Your Credit Score is Already Being Built \uD83D\uDCC9",
    body: "Even if you've never had a credit card, your credit history is forming. Payment history = 35% of your score. One missed payment can follow you for 7 years.",
    stat: "One missed payment can drop your score by 100 points.",
    emoji: "\uD83D\uDCC9",
    gradient: "from-purple-950 to-zinc-900",
  },
  {
    id: '8',
    category: 'credit',
    title: "The Credit Card Trick Nobody Teaches You \uD83D\uDCB3",
    body: "Use your credit card like a debit card: only spend what you already have. Pay the full balance every month. You build credit, get rewards, and pay zero interest.",
    stat: "People who pay in full monthly pay $0 in interest. Ever.",
    emoji: "\uD83D\uDCB3",
    gradient: "from-purple-950 to-zinc-900",
  },
  {
    id: '9',
    category: 'budgeting',
    title: "Emergency Fund: Not Optional \u26A1",
    body: "3-6 months of expenses in a high-yield savings account (HYSA). This is your financial immune system. Without it, one car repair or ER visit sends you into debt.",
    stat: "60% of Americans can't cover a $1,000 emergency.",
    emoji: "\u26A1",
    gradient: "from-blue-950 to-zinc-900",
  },
  {
    id: '10',
    category: 'investing',
    title: "Your Employer Match is Free Money \uD83D\uDCB0",
    body: "If your employer offers 401k matching, that's an instant 50-100% return on your contribution. Always contribute enough to get the full match \u2014 it's the best investment you'll ever make.",
    stat: "Average employer match: 4.4% of salary. Don't leave it behind.",
    emoji: "\uD83D\uDCB0",
    gradient: "from-green-950 to-zinc-900",
  },
]
